paths:
  /api/csv/insertData/{fileName}:
    post:
      tags:
        - csv
      summary: "CSV 저장"
      description: "csv_data 폴더 내의 파일을 읽어 Database로 저장합니다."
      parameters:
        - name: fileName
          in: path
          default: transaction_sample.csv
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean